### ISSUE TITLE
AttributeError: module 'tex2lms' has no attribute 'template_spreadsheet'. 

### ISSUE THREAD

**Issue by ll-portes** [viper2642/TeX2LMS#1]
In the last line of the Jupyter notebook LMSQuestionProcessing.ipynb the instruction `tex2lms.template_spreadsheet()` gives the error AttributeError: module 'tex2lms' has no attribute 'template_spreadsheet'. 

After inspecting the tex2lms.py file, I think it should be changed to `tex2lms.make_template_spreadsheet()`

**Comment by viper2642** [comment]
indeed, typo fixed in latest commit.
