### ISSUE TITLE
empty first column created with make_template_spreadsheet()

### ISSUE THREAD

**Issue by ll-portes** [viper2642/TeX2LMS#2]
If we run `tex2lms.make_template_spreadsheet()`, the new spreadsheet will have an empty first column. Because the provided example test_1_2022-1_MCQ.ods starts has no empty first column, maybe the new one created with `tex2lms.make_template_spreadsheet()` will be the source of upcoming errors if we used in `tex2lms.process_mcq_spreadsheet`.

**Comment by viper2642** [comment]
yes, I have added `"index=False"` in the arguments of the DataFrame function `to_excel` so that it does not save the index column (empty). In passing, the template spreadsheet has one row of data so that it can be processed through `tex2lms.process_mcq_spreadsheet`
